name: docker-build-push

on:
  workflow_dispatch:
    inputs:
      PG_VERSION:
        description: 'Postgres Major Version'
        required: true
        default: '15'
      TS_VERSION:
        description: 'Timescale Version'
        required: true
        default: '2.17.2'
      POSTGIS_MAJOR:
        description: 'Postgis Major Version'
        required: true
        default: '3'
      TS_TUNE_VERSION:
        description: 'Timescale Tune Version/Tag'
        required: true
        default: 'v0.18.0'
      TS_PARALLEL_COPY_VERSION:
        description: 'PTimescale Parallel Copy Version/Tag'
        required: true
        default: 'v0.7.1'
      BASE_OS:
        description: 'Base OS'
        required: true
        default: 'bookworm'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          tags: klajan/timescaledb-postgis:latest-pg${{ github.event.inputs.PG_VERSION }}
          build-args: |
            PG_VERSION=${{ github.event.inputs.PG_VERSION }}
            BASE_OS=${{ github.event.inputs.BASE_OS }}
            TS_VERSION=${{ github.event.inputs.TS_VERSION }}
            POSTGIS_MAJOR=${{ github.event.inputs.POSTGIS_MAJOR }}
            TS_TUNE_VERSION=${{ github.event.inputs.TS_TUNE_VERSION }}
            TS_PARALLEL_COPY_VERSION=${{ github.event.inputs.TS_PARALLEL_COPY_VERSION }}
